{% set name = "EWMHlib" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kalmat/EWMHlib/archive/v{{ version }}.tar.gz
  sha256: c63fc4ae9d43a6f7f0f5472bab38a599f2684b9cc3f368312416a4f06e49a408

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [not linux]
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-xlib >=0.21
    - typing_extensions >=4.4.0

test:
  commands:
    - pip check
    - "DISPLAY=localhost:1.0 XDG_SESSION_TYPE=x11 xvfb-run -a python -c 'import ewmhlib'"
  requires:
    - pip

about:
  home: https://github.com/Kalmat/EWMHlib
  summary: Extended Window Manager Hints implementation in Python 3 which allows to easily query and control Window Managers which follow these standards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - '0xbe7a'
